spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:db

  graphql:
    cors:
      allowed-headers: true
      allowed-origins: true
      allowed-methods: true
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
